## 배열의 일반 검색

In [4]:
import numpy as np
## 색인검색
v = np.array([1,2,3,4,5])
v[0] , v[-1]

A = np.array([[1,2,3,4,5],[6,7,8,9,10]])
A[0]
A[-1]

array([ 6,  7,  8,  9, 10])

In [9]:
## 슬라이스 검색
B = np.arange(9).reshape(3,3)
B
B.shape
B[0,:]
B[0]
B[:,0]

array([0, 3, 6])

In [13]:
## 생략기호를 사용한 접근
A = np.arange(1,60,5).reshape(3,4)
A
A[...]
A[...,:2]

array([[ 1,  6],
       [21, 26],
       [41, 46]])

## 논리식 검색과 팬시검색

In [14]:
## 논리 검색1
L = np.random.rand(7,4)
L

array([[0.62160401, 0.49438189, 0.59662617, 0.86330325],
       [0.03087089, 0.42031845, 0.1693272 , 0.67564251],
       [0.91752381, 0.246568  , 0.70241306, 0.12655192],
       [0.81985243, 0.53662672, 0.07929469, 0.40185884],
       [0.68220126, 0.73977655, 0.70562167, 0.88703257],
       [0.00589788, 0.27056941, 0.75433449, 0.61277656],
       [0.2213024 , 0.18497595, 0.52080635, 0.04679574]])

In [19]:
## 논리 검색2
L[L<0] =999
L
LC = L[L==999]
LC

SyntaxError: invalid syntax (1303755656.py, line 4)

In [22]:
## 논리 검색3
L = np.arange(0,12)
L
try:
    L and L
except Exception as e:
    print(e)

np.logical_and(L,L)
L[np.logical_and(L,L)]

The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [23]:
## 팬시 검색1
x = np.arange(1,15)
x


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [24]:
pos2 = np.array([1,2,2,2])
x[pos2]

array([2, 3, 3, 3])

In [25]:
c=x[pos2]
np.may_share_memory(x,c)


False

In [26]:
y = x[:4]
np.may_share_memory(x,y)

True

In [27]:
# 팬시 검색2
x = np.arange(16).reshape(4,4)
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [28]:
x[[3,0]]

array([[12, 13, 14, 15],
       [ 0,  1,  2,  3]])

In [29]:
x[[1,2],[2,3]]

array([ 6, 11])

In [30]:
a = np.array([[2,3,4,5],[8,9,0,1]])
a

array([[2, 3, 4, 5],
       [8, 9, 0, 1]])

In [32]:
a[np.ix_([0,1],[0,1])]

array([[2, 3],
       [8, 9]])

In [33]:
# 팬시 검색 혼용
x = np.arange(10).reshape(2,5)
x

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [34]:
x[0,[0,1]]

array([0, 1])

In [35]:
x[1,[0,1]]

array([5, 6])

In [36]:
x[[0,1]]

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [37]:
x[[0,1],0]

array([0, 5])

In [39]:
a=x[[0,1],0]
a

array([0, 5])

In [40]:
np.may_share_memory(x,a)

False

In [41]:
# 팬시검색을 이용한 축소 및 확대
x = np.arange(9).reshape(3,3)
x

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [43]:
a = x[1:,1:]
a

array([[4, 5],
       [7, 8]])

In [44]:
np.may_share_memory(x,a)

True

In [45]:
a=np.reshape(np.arange(10),(2,5))
a

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [49]:
c = a[[1,1,1],np.newaxis]
c

array([[[5, 6, 7, 8, 9]],

       [[5, 6, 7, 8, 9]],

       [[5, 6, 7, 8, 9]]])

## 메소드나 함수로 검색하기

In [51]:
# 메소드로 검색1
x = np.arange(9).reshape(3,3)
x

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [52]:
x.item(1)

1

In [53]:
x.item(5)

5

In [54]:
x.item(1,2)

5

In [55]:
x.item(2,2)

8

In [57]:
x.itemset(2,20)
x

array([[ 0,  1, 20],
       [ 3,  4,  5],
       [ 6,  7,  8]])

In [58]:
x.itemset((1,2),20)
x

array([[ 0,  1, 20],
       [ 3,  4, 20],
       [ 6,  7,  8]])

In [59]:
x.view()

array([[ 0,  1, 20],
       [ 3,  4, 20],
       [ 6,  7,  8]])

In [60]:
b = np.linspace(1,10,10).reshape(2,5)
b

array([[ 1.,  2.,  3.,  4.,  5.],
       [ 6.,  7.,  8.,  9., 10.]])

In [61]:
pos1 = [3,4]
b.take(pos1)

array([4., 5.])

In [62]:
pos2=[[0,1],[3,4]]
b.take(pos2)

array([[1., 2.],
       [4., 5.]])