## 파이썬과 넘파이 모듈 차이점 이해하기
- 배열 구조 이해하기

In [2]:
l = [[1,2,3],[4,5,6]]
type(l)

list

In [3]:
l[0],l[1]

([1, 2, 3], [4, 5, 6])

In [4]:
for i,a in enumerate(l):
    for j,b in enumerate(a):
        print(l[i][j])

1
2
3
4
5
6


In [5]:
import numpy as np
np.__version__

'1.26.4'

In [6]:
print(np.ndarray)

<class 'numpy.ndarray'>


In [7]:
np.ndarray.__name__

'ndarray'

In [8]:
for i in dir(np.ndarray):
    if not i.startswith('_'):
        if type(np.ndarray.__dict__[i]) != type(np.ndarray.var):
            print(i)

T
base
ctypes
data
dtype
flags
flat
imag
itemsize
nbytes
ndim
real
shape
size
strides


- 다차원 배열 만들기

In [9]:
l=[1,2,3,4]
a=np.array(l)
a

array([1, 2, 3, 4])

In [10]:
type(a)

numpy.ndarray

In [11]:
t = (1,2,3,4)
b = np.array(t)
type(b)

numpy.ndarray

- 다차원 배열 데이터 관리

In [12]:
a.data

In [13]:
a.data.obj

array([1, 2, 3, 4])

In [14]:
type(a.data.obj)

numpy.ndarray

In [15]:
## 다차원 배열 자료형 관리
e = np.array(l,dtype=np.float_)
e

array([1., 2., 3., 4.])

In [16]:
e.dtype

dtype('float64')

In [17]:
## 2차원 배열의 정보 확인
a2 = np.array([[1,2,3],[4,5,6]])
a2.shape

(2, 3)

In [18]:
a2.ndim

2

In [19]:
a2.dtype

dtype('int32')

In [20]:
a2.itemsize

4

In [21]:
a2.size

6

In [22]:
a2.strides

(12, 4)

In [23]:
## 대표적인 다차원 배열
np.ndarray.__bases__

(object,)

In [24]:
np.matrix.__bases__

(numpy.ndarray,)

In [25]:
## 함수와 메소드
(a!=0).any

<function ndarray.any>

In [26]:
np.any

<function any at 0x0000028E123B8F30>

In [27]:
np.ndarray.any is np.core.fromnumeric.any

False

In [28]:
## 같은 이름의 함수와 메소드
np_ =set(dir(np))
np_

{'ALLOW_THREADS',
 'BUFSIZE',
 'CLIP',
 'DataSource',
 'ERR_CALL',
 'ERR_DEFAULT',
 'ERR_IGNORE',
 'ERR_LOG',
 'ERR_PRINT',
 'ERR_RAISE',
 'ERR_WARN',
 'FLOATING_POINT_SUPPORT',
 'FPE_DIVIDEBYZERO',
 'FPE_INVALID',
 'FPE_OVERFLOW',
 'FPE_UNDERFLOW',
 'False_',
 'Inf',
 'Infinity',
 'MAXDIMS',
 'MAY_SHARE_BOUNDS',
 'MAY_SHARE_EXACT',
 'NAN',
 'NINF',
 'NZERO',
 'NaN',
 'PINF',
 'PZERO',
 'RAISE',
 'RankWarning',
 'SHIFT_DIVIDEBYZERO',
 'SHIFT_INVALID',
 'SHIFT_OVERFLOW',
 'SHIFT_UNDERFLOW',
 'ScalarType',
 'True_',
 'UFUNC_BUFSIZE_DEFAULT',
 'UFUNC_PYVALS_NAME',
 'WRAP',
 '_CopyMode',
 '_NoValue',
 '_UFUNC_API',
 '__NUMPY_SETUP__',
 '__all__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__deprecated_attrs__',
 '__dir__',
 '__doc__',
 '__expired_functions__',
 '__file__',
 '__former_attrs__',
 '__future_scalars__',
 '__getattr__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_add_newdoc_ufunc',
 '_builtins',
 '_distributor_init',
 '_financi

In [29]:
nd_=set(dir(np.ndarray))

In [30]:
npd_ = np_&nd_

In [31]:
len(npd_)

48

In [32]:
count = 0
for i in list(npd_):
    count+=1
    print(i,end=" ")
    if count % 5 ==0:
        print()

real nbytes __dir__ argmin std 
conjugate resize cumsum nonzero sum 
take any dot prod size 
copy trace swapaxes clip sort 
round argpartition squeeze shape reshape 
ptp all dtype ravel cumprod 
var conj ndim argmax max 
mean imag __doc__ transpose choose 
searchsorted put min compress diagonal 
argsort partition repeat 

In [33]:
# 유니버셜 함수
a = dir(np)
np.ufunc

numpy.ufunc

In [34]:
# count = 0
# for i in a:
#     if i == "Tester":
#         continue
#     if type(np.__dict__[i]) == np.ufunc:
#         print(i,end=" ")
#         count+=1
#         if count %5 ==0:
#             print()

In [35]:
# 백터화 연산
a = np.arange(6,10)
a

array([6, 7, 8, 9])

In [36]:
b = np.arange(10,14)
b

array([10, 11, 12, 13])

In [37]:
c = a*b
c

array([ 60,  77,  96, 117])

In [38]:
# 축 연산
a2 = np.array([1,2,3,4])
a2

array([1, 2, 3, 4])

In [39]:
a2 = a2.reshape(2,2)
a2

array([[1, 2],
       [3, 4]])

In [40]:
np.sum(a2)

10

In [41]:
np.sum(a2,axis=0)

array([4, 6])

In [42]:
np.sum(a2,axis=1)

array([3, 7])

In [43]:
## 배여르이 원소 개수 일치
a = np.array([4,5])
a.shape

(2,)

In [44]:
b = np.array([3,4,5])
b.shape

(3,)

In [45]:
try:
    a+b
except Exception as e:
    print(e)

operands could not be broadcast together with shapes (2,) (3,) 


## 배열 할당과 검색

In [46]:
## 배영ㄹ을 다른 변수에 할당
a = np.array([[1,2],[3,4]])
a

array([[1, 2],
       [3, 4]])

In [47]:
b =a
b

array([[1, 2],
       [3, 4]])

In [48]:
b[0]=999
a

array([[999, 999],
       [  3,   4]])

In [49]:
b

array([[999, 999],
       [  3,   4]])

In [50]:
## 배열의 복사/뷰 확인
f = np.array([4,5,6,7,8])
e = f.copy()

In [51]:
g = f[:]
g.base

array([4, 5, 6, 7, 8])

In [52]:
np.may_share_memory(g,f)

True

In [53]:
## 리스트 검색
l = list(range(1,10))
l

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [54]:

index = 1
l.__getitem__(index)

2

In [55]:
index = slice(1,3)
l.__getitem__(index)

[2, 3]

In [56]:
## 다차원 배열 검색 2
index = 1
a.__getitem__(index)


array([3, 4])

In [57]:
index = [1]
a.__getitem__(index)

array([[3, 4]])

In [58]:
index = a<4
index

array([[False, False],
       [ True, False]])

In [59]:
a.__getitem__(index)

array([3])

## 선형대수 기본 알아보기

In [60]:
## Scalar - 0차원
a = np.array(43)
type(a)

numpy.ndarray

In [61]:
a

array(43)

In [62]:
a.ndim

0

In [63]:
a.shape

()

In [64]:
a.dtype

dtype('int32')

In [65]:
a == 43

True

In [66]:
## Vector 1차원
v = np.array([43])
type(v)

numpy.ndarray

In [67]:
v

array([43])

In [68]:
v.ndim

1

In [69]:
v.shape

(1,)

In [70]:
## 백터 생성 함수 1
v = np.arange(20)
v

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [71]:
v.dtype

dtype('int32')

In [72]:
v1 = np.arange(10.5,20.5,0.5)
v1

array([10.5, 11. , 11.5, 12. , 12.5, 13. , 13.5, 14. , 14.5, 15. , 15.5,
       16. , 16.5, 17. , 17.5, 18. , 18.5, 19. , 19.5, 20. ])

In [73]:
v1.dtype

dtype('float64')

In [74]:
v1.size

20

In [75]:
## 백터 생성 함수2
la = np.linspace(1,10,10)
la

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [76]:
la.dtype

dtype('float64')

In [77]:
lal = np.linspace(1,10,10,endpoint = False,retstep=True)
lal

(array([1. , 1.9, 2.8, 3.7, 4.6, 5.5, 6.4, 7.3, 8.2, 9.1]), 0.9)

In [78]:
## 백터 생성 함수 3 
lo = np.logspace(0,2,4)
lo

array([  1.        ,   4.64158883,  21.5443469 , 100.        ])

In [79]:
la2 = np.linspace(0,2,4)
la2

array([0.        , 0.66666667, 1.33333333, 2.        ])

In [80]:
for i in la2:
    print(np.power(10,i))

1.0
4.641588833612778
21.544346900318832
100.0


In [81]:
## 백터 크기
v = np.arange(3,5)
v

array([3, 4])

In [82]:
np.hypot(v[0],v[1])

5.0

In [83]:
v_p = np.power(v,2)
v_r = np.sqrt(np.sum(v_p))
v_r

5.0

In [84]:
np.linalg.norm(v)

5.0

In [85]:
## 표준 단위 백터
e1 = np.array([1,0,0])
np.linalg.norm(e1)

1.0

In [86]:
e2 = np.array([0,1,0])
np.linalg.norm(e2)

1.0

In [87]:
e3 = np.array([0,0,1])
np.linalg.norm(e3)

1.0

In [88]:
## 단위 백터
v_3 = np.array([1,2,3])
v_3_n = np.linalg.norm(v_3)
v_3_n

3.7416573867739413

In [89]:
v_3_u = v_3/v_3_n
v_3_u

array([0.26726124, 0.53452248, 0.80178373])

In [90]:
np.linalg.norm(v_3_u)

1.0

In [91]:
## 백터의 상등
a = np.arange(3,5)
b = np.arange(3,5)
np.array_equal(a,b)

True

In [92]:
a_1 = np.linalg.norm(a)
b_1 = np.linalg.norm(b)
a_1 == b_1

True

In [93]:
## 백터의 거리
c = np.arange(10,13)
d = np.arange(0,3)
np.sqrt(np.sum(np.square(c-d)))
np.linalg.norm(c-d)

17.320508075688775

## 행렬(Matrix) 알아보기

In [95]:
# 행렬 만들기
A = np.array([[43],[44]])
type(A)
A

array([[43],
       [44]])

In [98]:
A.dtype
A.ndim
A.shape

(2, 1)

In [99]:
# 행렬 랭크
c1 = np.array([[1,2,4],[2,4,8],[3,4,5]])
np.linalg.matrix_rank(c1)

2

In [100]:
c2 = np.array([[1,3,4],[1,8,5],[2,3,4]])
np.linalg.matrix_rank(c2)

3

In [101]:
np.linalg.det(c1)

0.0

In [102]:
c1[0]*2 - c1[1]

array([0, 0, 0])

In [103]:
np.linalg.det(c2)

-17.0

In [104]:
np.linalg.matrix_rank(c2.T)

3

In [105]:
# 축 알아보기1
A = np.array([[2,3],[4,5]])
A.sum()

14

In [107]:
A.sum(axis=0)
A.sum(axis=1)

array([5, 9])

In [109]:
# 축 알아보기2
C = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
C.ndim

3

In [110]:
C.shape

(2, 2, 2)

In [111]:
C[0]

array([[1, 2],
       [3, 4]])

In [112]:
C[1]

array([[5, 6],
       [7, 8]])

In [113]:
C.sum(axis=0)

array([[ 6,  8],
       [10, 12]])

In [114]:
C.sum(axis=1)

array([[ 4,  6],
       [12, 14]])

In [115]:
C.sum(axis=2)

array([[ 3,  7],
       [11, 15]])

In [116]:
# 확장 및 축소하기
# 차원 확장
x = np.array([1,2])
x

array([1, 2])

In [117]:
y = np.expand_dims(x,axis=1)
y

array([[1],
       [2]])

In [118]:
z = np.expand_dims(x,axis=0)
z

array([[1, 2]])

In [119]:
# 차원 축소
x = np.array([[1,4,5],[4,5,6],[7,8,9]])
x

array([[1, 4, 5],
       [4, 5, 6],
       [7, 8, 9]])

In [121]:
x.flatten()

array([1, 4, 5, 4, 5, 6, 7, 8, 9])

In [122]:
x.ravel()

array([1, 4, 5, 4, 5, 6, 7, 8, 9])

## 행렬 종류 알아보기

In [123]:
# 정사각행렬
a = np.array([[1,2,3],[4,5,6],[7,8,8]])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 8]])

In [124]:
a.shape

(3, 3)

In [125]:
np.trace(a)

14

In [127]:
a.trace()

14

In [129]:
# 대각행렬
b = np.array([[1,0,0],[0,3,0],[0,0,5]])
b

array([[1, 0, 0],
       [0, 3, 0],
       [0, 0, 5]])

In [130]:
b.diagonal()

array([1, 3, 5])

In [131]:
np.diagonal(b)

array([1, 3, 5])

In [132]:
# 삼각행렬
a = np.arange(1,10).reshape(3,3)
a


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [133]:
np.tril(a)

array([[1, 0, 0],
       [4, 5, 0],
       [7, 8, 9]])

In [135]:
a = np.arange(1,10).reshape(3,3)
np.triu(a)

array([[1, 2, 3],
       [0, 5, 6],
       [0, 0, 9]])

In [136]:
# 대칭행렬
X = np.array([[1,2,3],[4,5,6],[7,8,8]])
X

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 8]])

In [137]:
X.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 8]])

In [138]:
np.array_equal(X,X.T)

False

In [139]:
np.array_equiv(X,X.T)

False

In [141]:
# 치환행렬
a=np.arange(1,10).reshape(3,3)
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [142]:
b = np.eye(3,dtype='int')
b

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [143]:
np.dot(a,b)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [144]:
c = np.array([[0,1,0],[1,0,0],[0,0,1]])
np.dot(a,c)

array([[2, 1, 3],
       [5, 4, 6],
       [8, 7, 9]])

In [145]:
# 전치행렬
a = np.array([[1,2],[3,4]])
a

array([[1, 2],
       [3, 4]])

In [146]:
a.T

array([[1, 3],
       [2, 4]])

In [147]:
a.transpose()

array([[1, 3],
       [2, 4]])

In [148]:
np.transpose(a)

array([[1, 3],
       [2, 4]])

## 다차원 배열의 검색

In [149]:
# 색인검색
v = np.array([1,2,3,4,5])
v[0]

1

In [150]:
v[-1]

5

In [151]:
A = np.array([[1,2,3,4,5],[6,7,8,9,10]])
A[0]

array([1, 2, 3, 4, 5])

In [152]:
A[-1]

array([ 6,  7,  8,  9, 10])

In [156]:
# 슬라이스 검색
B = np.arange(9).reshape(3,3)
B

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [157]:
B.shape

(3, 3)

In [158]:
B[0,:]

array([0, 1, 2])

In [159]:
B[0]

array([0, 1, 2])

In [160]:
B[:,0]

array([0, 3, 6])

In [161]:
# 생략기호를 사용한 접근
A = np.arange(1,60,5).reshape(3,4)
A

array([[ 1,  6, 11, 16],
       [21, 26, 31, 36],
       [41, 46, 51, 56]])

In [162]:
A[...]

array([[ 1,  6, 11, 16],
       [21, 26, 31, 36],
       [41, 46, 51, 56]])

In [163]:
A[:2,...]

array([[ 1,  6, 11, 16],
       [21, 26, 31, 36]])

In [164]:
A[...,:2]

array([[ 1,  6],
       [21, 26],
       [41, 46]])

## 논리식 검색과 팬시검색

In [166]:
L = np.random.randn(7,4)
L

array([[-0.68551701, -0.25197719,  0.57856756,  0.04030973],
       [ 1.03778664, -0.57411024, -0.53661195,  0.10648688],
       [-0.31634887,  0.12161922,  0.8494827 ,  1.4101638 ],
       [ 1.2532136 ,  0.61627368, -0.2900817 , -1.49193066],
       [ 0.08023162,  0.32623283, -0.85778194, -0.29873542],
       [-0.18144639, -1.47488855, -0.91826969, -0.74119858],
       [ 0.29148285,  0.46348957,  0.45181255, -1.06393377]])

In [167]:
L[L<0]

array([-0.68551701, -0.25197719, -0.57411024, -0.53661195, -0.31634887,
       -0.2900817 , -1.49193066, -0.85778194, -0.29873542, -0.18144639,
       -1.47488855, -0.91826969, -0.74119858, -1.06393377])

In [169]:
# 논리 검색2
L[L<0] =999
L

array([[9.99000000e+02, 9.99000000e+02, 5.78567559e-01, 4.03097264e-02],
       [1.03778664e+00, 9.99000000e+02, 9.99000000e+02, 1.06486883e-01],
       [9.99000000e+02, 1.21619223e-01, 8.49482700e-01, 1.41016380e+00],
       [1.25321360e+00, 6.16273678e-01, 9.99000000e+02, 9.99000000e+02],
       [8.02316205e-02, 3.26232830e-01, 9.99000000e+02, 9.99000000e+02],
       [9.99000000e+02, 9.99000000e+02, 9.99000000e+02, 9.99000000e+02],
       [2.91482851e-01, 4.63489569e-01, 4.51812550e-01, 9.99000000e+02]])

In [170]:
LC = L[L==999]
LC

array([999., 999., 999., 999., 999., 999., 999., 999., 999., 999., 999.,
       999., 999., 999.])

In [171]:
# 논리 검색3
L = np.arange(0,12)
L

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [172]:
try:
    L and L
except Exception as e:
    print(e)

The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()


In [173]:
np.logical_and(L,L)

array([False,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True])

In [174]:
L[np.logical_and(L,L)]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [175]:
# 팬시 검색1
x = np.arange(1,15)
x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [176]:
pos2 = np.array([1,2,2,2])
x[pos2]
##????

array([2, 3, 3, 3])

In [178]:
c = x[pos2]
np.may_share_memory(x,c)

False

In [179]:
y = x[:4]
np.may_share_memory(x,y)

True