### Tensor 이해

In [1]:
### 모듈 로딩
import torch

- Tensor 생성 [2] torch.rand() 

In [2]:
# 0 <= ~ <1 범위의 임의의 숫자 1개 추출 => rand
torch.manual_seed(1)

dataTS = torch.rand(1,2,3)
# rand(*size) : 가변인자 ==> 몇 차원이지 알 수 없음!
# *size => *는 가변인자를 나타냄.

In [3]:
dataTS

tensor([[[0.7576, 0.2793, 0.4031],
         [0.7347, 0.0293, 0.7999]]])

In [4]:
dataTS = torch.rand(2,2,3)

In [5]:
dataTS

tensor([[[0.3971, 0.7544, 0.5695],
         [0.4388, 0.6387, 0.5247]],

        [[0.6826, 0.3051, 0.4635],
         [0.4550, 0.5725, 0.4980]]])

In [9]:
dataTS1 = torch.rand(3)        # 1D  Vector
dataTS2 = torch.rand(2,3)      # 2D  Maxtrix
dataTS3 = torch.rand(2,1,3)    # 3D  3D Tensor

In [10]:
print(dataTS1,dataTS2,dataTS3,sep='\n')

tensor([0.0444, 0.0246, 0.2588])
tensor([[0.9391, 0.4167, 0.7140],
        [0.2676, 0.9906, 0.2885]])
tensor([[[0.8750, 0.5059, 0.2366]],

        [[0.7570, 0.2346, 0.6471]]])


- Tensor 생성 [3] torch.randn()

In [12]:
dataTS1 = torch.randn(3)        # 1D  Vector
dataTS2 = torch.randn(2,3)      # 2D  Maxtrix
dataTS3 = torch.randn(2,1,3)    # 3D  3D Tensor
print(dataTS1,dataTS2,dataTS3,sep='\n')

tensor([0.2366, 0.2857, 0.6898])
tensor([[-0.6331,  0.8795, -0.6842],
        [ 0.4533,  0.2912, -0.8317]])
tensor([[[-0.5525,  0.6355, -0.3968]],

        [[-0.6571, -1.6428,  0.9803]]])


* Tensor 생성 [4] torch.randint()

In [18]:
# 1D Vector
dataTS1=torch.randint(1,46,(1,6))
#                    -> size 부분
dataTS1

In [21]:
# 2D Vector
dataTS2=torch.randint(1,46,(4,6))
#                    -> size 부분
dataTS2

tensor([[32, 25,  2, 36, 33, 33],
        [13, 14,  4, 19, 36, 40],
        [44, 15, 40, 40, 29,  1],
        [19, 35, 42,  1, 36, 24]])