### Tensor 이해 - 생성
- Tensor란?
    * pytorch에서 데이터를 저장하는 객체
    * 모델에 입력/출력 데이터 형태
- 개발 버전 : torch V.2.4.1
-----------------------------------------------------------------------------


- 정수 int ===> 크기 다양
    * byte => 8bit => 256개 => int8 / unit8
        - 부호(-/+) : -128 ~ 0 ~ +127 : -2^7 ~ 2^7-1
        - 부호 X : 0 ~ 255 ===> (이미지데이터 픽셀 픽셀 색상값)
    * short => 16비트 => -2^(15) ~ +2^(15)-1 ==> int16/unit16
    * int => 32비트 => int32/unit32
    * long int => 64비트 => int64/unit64

- 데이터타입 변수명 = 데이터  
int age = 10

- 기본 데이터 타입 => 숫자, 글자 ==> int,float,char,bool  
    - C/C++/C#/Java ==> 스택
    - python => 힙 (클래스기반 객체)  
- 확장 데이이터 타입 => 여러개의 기본 데이터 타입 모여서 하나의 데이터 표현 [string(얘는 언어에 따라서 다름)]
    - C => 구조체
    - Java와 OOP => 구조체 + 함수 => 클래스
    - C/C++/C#/Java ==> 힙(클래스기반 객체)

- 실수 3.12 ===> 정수부 3, 실수부 12
    * 실수 float => 소수점 이하 자릿수
    * flota => 7/8           4바이트 int32
    * double => float 소수점 2배  8바이트 double
    -----------------------------------------------------------------------------

### 원하는 값으로 채원 텐서 생성 -> torch.tensor( 데이터 ) 

In [6]:
import torch

# --------------------------------
# 함수기능 : 텐서 속성 정보 출력 함수
# --------------------------------

def printInfo(obj,obj_name):
    print(f'\n[{obj_name}]')
    print(f'shape : {obj.shape}')
    print(f'ndim : {obj.ndim}차원')
    print(f'dtype : {obj.dtype}')
    print(f'device : {obj.device}')
    print(f'data : \n{obj.data}')

In [7]:
print(torch.__version__)

2.4.1


* 텐서 생성 [1] torch.tensor()

In [10]:
## 데이터 1개 즉, 스칼라 0D
dataTF=torch.tensor(10)
printInfo(dataTF,'dataTF')

dataTF=torch.tensor(10,dtype=torch.int8)
printInfo(dataTF,'dataTF')

dataTF=torch.tensor(10,dtype=torch.uint8) # u => unsigned로 잡음.
printInfo(dataTF,'dataTF')


[dataTF]
shape : torch.Size([])
ndim : 0차원
dtype : torch.int64
device : cpu
data : 
10

[dataTF]
shape : torch.Size([])
ndim : 0차원
dtype : torch.int8
device : cpu
data : 
10

[dataTF]
shape : torch.Size([])
ndim : 0차원
dtype : torch.uint8
device : cpu
data : 
10


In [12]:
## 데이터 1개 즉, 백터 1D
dataTF=torch.tensor([],dtype=torch.int8)
printInfo(dataTF,'dataTF')

dataTF=torch.tensor([10],dtype=torch.uint8) # u => unsigned로 잡음.
printInfo(dataTF,'dataTF')



[dataTF]
shape : torch.Size([0])
ndim : 1차원
dtype : torch.int8
device : cpu
data : 
tensor([], dtype=torch.int8)

[dataTF]
shape : torch.Size([1])
ndim : 1차원
dtype : torch.uint8
device : cpu
data : 
tensor([10], dtype=torch.uint8)


In [15]:
## 데이터 1개 즉, 백터 2D
dataTF=torch.tensor([[10]],dtype=torch.int8)
printInfo(dataTF,'dataTF')

dataTF=torch.tensor([[10],[20]],dtype=torch.uint8) # u => unsigned로 잡음.
printInfo(dataTF,'dataTF')


[dataTF]
shape : torch.Size([1, 1])
ndim : 2차원
dtype : torch.int8
device : cpu
data : 
tensor([[10]], dtype=torch.int8)

[dataTF]
shape : torch.Size([2, 1])
ndim : 2차원
dtype : torch.uint8
device : cpu
data : 
tensor([[10],
        [20]], dtype=torch.uint8)


In [18]:
## 데이터 1개 즉, ND
dataTF=torch.tensor([[[[[[10]]]]]],dtype=torch.int8)
printInfo(dataTF,'dataTF')

dataTF=torch.tensor([[[[10]],[[20]]]],dtype=torch.uint8) # u => unsigned로 잡음.
printInfo(dataTF,'dataTF')


[dataTF]
shape : torch.Size([1, 1, 1, 1, 1, 1])
ndim : 6차원
dtype : torch.int8
device : cpu
data : 
tensor([[[[[[10]]]]]], dtype=torch.int8)

[dataTF]
shape : torch.Size([1, 2, 1, 1])
ndim : 4차원
dtype : torch.uint8
device : cpu
data : 
tensor([[[[10]],

         [[20]]]], dtype=torch.uint8)


In [19]:
## 대각선으로 1로 채운 텐서 생성 -> torch.eye()