In [121]:
import pandas as pd
import numpy as np

file_name = 'ch2_scores_em.csv'
df = pd.read_csv(file_name,index_col='student number')

print(df.head())

scores = np.array(df['english'])[:10]
print(scores)

scores_df = pd.DataFrame({'score':scores},
                         index=pd.Index(['A','B','C','D','E','F','G','H','I','J'],
                         name = 'student'))

print(scores_df)


                english  mathematics
student number                      
1                    42           65
2                    69           80
3                    56           63
4                    41           63
5                    57           76
[42 69 56 41 57 48 65 49 65 58]
         score
student       
A           42
B           69
C           56
D           41
E           57
F           48
G           65
H           49
I           65
J           58


In [122]:
sum(scores)

550

In [123]:
np.mean(scores)

55.0

In [124]:
scores_df.mean()

score    55.0
dtype: float64

In [125]:
sorted_scores = np.sort(scores)
sorted_scores

array([41, 42, 48, 49, 56, 57, 58, 65, 65, 69], dtype=int64)

In [126]:
mean = np.mean(scores)
deviation = scores - mean
deviation

array([-13.,  14.,   1., -14.,   2.,  -7.,  10.,  -6.,  10.,   3.])

In [127]:
summary_df = scores_df.copy()
summary_df['deviation'] = deviation
summary_df

score  deviation
student                  
A           42      -13.0
B           69       14.0
C           56        1.0
D           41      -14.0
E           57        2.0
F           48       -7.0
G           65       10.0
H           49       -6.0
I           65       10.0
J           58        3.0

In [128]:
summary_df.mean()

score        55.0
deviation     0.0
dtype: float64

In [129]:
# 분산
np.mean(deviation**2)

86.0

In [130]:
np.var(scores)

86.0

In [131]:
scores_df.var()

score    95.555556
dtype: float64

In [132]:
summary_df['square of deviation'] = np.square(deviation)
summary_df

score  deviation  square of deviation
student                                       
A           42      -13.0                169.0
B           69       14.0                196.0
C           56        1.0                  1.0
D           41      -14.0                196.0
E           57        2.0                  4.0
F           48       -7.0                 49.0
G           65       10.0                100.0
H           49       -6.0                 36.0
I           65       10.0                100.0
J           58        3.0                  9.0

In [133]:
# 표준편차
np.sqrt(np.var(scores,ddof = 0))

9.273618495495704

In [134]:
np.std(scores,ddof=0)

9.273618495495704

In [135]:
scores_Q1 = np.percentile(scores,25)
scores_Q3 = np.percentile(scores,75)
scores_IQR = scores_Q3-scores_Q1
scores_IQR

15.0

In [136]:
pd.Series(scores).describe()

count    10.000000
mean     55.000000
std       9.775252
min      41.000000
25%      48.250000
50%      56.500000
75%      63.250000
max      69.000000
dtype: float64

In [137]:
z =(scores - np.mean(scores)) / np.std(scores)
z

array([-1.40182605,  1.50965882,  0.10783277, -1.50965882,  0.21566555,
       -0.75482941,  1.07832773, -0.64699664,  1.07832773,  0.32349832])

In [138]:
np.mean(z),np.std(z,ddof=0)

(-1.6653345369377347e-17, 0.9999999999999999)

In [139]:
z= 50 + 10 * (scores - np.mean(scores))/np.std(scores)
z

array([35.98173948, 65.09658825, 51.07832773, 34.90341175, 52.15665546,
       42.45170588, 60.78327732, 43.53003361, 60.78327732, 53.2349832 ])

In [140]:
scores_df['deviation value'] = z
scores_df

score  deviation value
student                        
A           42        35.981739
B           69        65.096588
C           56        51.078328
D           41        34.903412
E           57        52.156655
F           48        42.451706
G           65        60.783277
H           49        43.530034
I           65        60.783277
J           58        53.234983

In [141]:
english_scores = np.array(df['english'])
pd.Series(english_scores).describe()

count    50.000000
mean     58.380000
std       9.799813
min      37.000000
25%      54.000000
50%      57.500000
75%      65.000000
max      79.000000
dtype: float64

In [142]:
freq, _ =np.histogram(english_scores,bins = 10,range=(0,100))
freq

array([ 0,  0,  0,  2,  8, 16, 18,  6,  0,  0], dtype=int64)

In [150]:
freq = np.histogram(english_scores,bins=10,range=(0,100))
freq

(array([ 0,  0,  0,  2,  8, 16, 18,  6,  0,  0], dtype=int64),
 array([  0.,  10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.]))

In [144]:
freq, _=np.histogram(english_scores,bins=10,range = (0,100))
rel_freq = freq / freq.sum()
rel_freq


array([0.  , 0.  , 0.  , 0.04, 0.16, 0.32, 0.36, 0.12, 0.  , 0.  ])

In [145]:
cum_rel_freq=np.cumsum(rel_freq)
cum_rel_freq

array([0.  , 0.  , 0.  , 0.04, 0.2 , 0.52, 0.88, 1.  , 1.  , 1.  ])

In [149]:
freq_class = [f'{i}~{i+10}' for i in range(0,100,10)]
freq_dist_df = pd.DataFrame({'frequency':freq},
                             index=pd.Index(freq_class,
                             name='class'))
class_value = [i+(i+10)//2 for i in range(0,100,0)]
#freq_dist_df['class value'] = class_value
freq_class


['0~10',
 '10~20',
 '20~30',
 '30~40',
 '40~50',
 '50~60',
 '60~70',
 '70~80',
 '80~90',
 '90~100']

In [ ]:
en_scores = np.array(df['english'])[:10]
ma_scores = np.array(df['mathematics'])[:10]
scores_df = pd.DataFrame({'english':en_scores,
                          'mathematics':ma_scores},
                         index = pd.Index(['A','B','C','D','E','F',
                                           'G','H','I','J'],
                                           name = 'student'))

In [ ]:
scores_df

english  mathematics
student                      
A             42           65
B             69           80
C             56           63
D             41           63
E             57           76
F             48           60
G             65           81
H             49           66
I             65           78
J             58           82