##### Torchmetrics  패키지
- pytorch에서 모델 성능평가 기능 제공 패키지
- 추가 설치 필요 
    * pip : pip install torchmetrics
    * conda : conda install -c conda-forge torchmetrics
- 사용법
    * 클래스 방식 : 인스턴스 생성 후 사용
    * 함수 방식 : 바로 사용 

- [1] 회귀(Regression) 성능지표

In [64]:
# 모듈 로딩
from torchmetrics.functional.regression import r2_score 
from torchmetrics.regression import R2Score
import torch 

In [65]:
# 클래스 방식 --------------------------------------------
# 데이터
target = torch.tensor([3, -0.5, 2, 7])  # 1D (4,)
preds = torch.tensor([2.5, 0.0, 2, 8])  # 1D (4,)

# 성능평가 => R2Score : 0 ~ 1(좋음) 정답에 얼마나 근사하게 표현했는가 
# r2score = R2Score()
# r2score(preds, target)
print( R2Score()(preds, target) )

tensor(0.9486)


In [66]:
# 함수 방식 --------------------------------------------------
# 데이터
target = torch.tensor([3, -0.5, 2, 7])  # 1D (4,)
preds = torch.tensor([2.5, 0.0, 2, 8])  # 1D (4,)

# 성능평가 => r2_score : 0 ~ 1(좋음) 정답에 얼마나 근사하게 표현했는가 
r2_score(preds, target)

tensor(0.9486)

In [67]:
# 모듈 로딩
from torchmetrics.functional.regression import mean_squared_error, mean_absolute_error 
from torchmetrics.regression import MeanSquaredError, MeanAbsoluteError
import torch 

In [68]:
# 데이터 
target = torch.tensor([2.5, 5.0, 4.0, 8.0])
preds = torch.tensor([3.0, 5.0, 2.5, 7.0])

# 성능평가 => 오차계산 : 0에 가까울 수록 좋은 것  
meansquarederror = MeanSquaredError()
print( meansquarederror(preds, target) )
print( MeanSquaredError()(preds, target) )

tensor(0.8750)
tensor(0.8750)


In [69]:
# 데이터 
target = torch.tensor([2.5, 5.0, 4.0, 8.0])
preds = torch.tensor([3.0, 5.0, 2.5, 7.0])

# 오차계산 
mean_squared_error(preds, target)


tensor(0.8750)

In [75]:
from torchmetrics.classification import F1Score, BinaryAccuracy, Accuracy
from torchmetrics.classification import ConfusionMatrix, BinaryConfusionMatrix, MulticlassConfusionMatrix

from torchmetrics.functional.classification import f1_score, binary_accuracy

In [76]:
target = torch.tensor([1, 1, 0, 0])
preds = torch.tensor([0, 1, 0, 0])

confmat = ConfusionMatrix(task="binary", num_classes=2)
confmat(preds, target)

tensor([[2, 0],
        [1, 1]])

In [77]:
target = torch.tensor([[0, 1, 0], [1, 0, 1]])
preds = torch.tensor([[0, 0, 1], [1, 0, 1]])

confmat = ConfusionMatrix(task="multilabel", num_labels=3)
confmat(preds, target)

tensor([[[1, 0],
         [0, 1]],

        [[1, 0],
         [1, 0]],

        [[0, 1],
         [0, 1]]])

In [78]:
target = torch.tensor([1, 1, 0, 0])
preds = torch.tensor([0, 1, 0, 0])

bcm = BinaryConfusionMatrix()
bcm(preds, target)

tensor([[2, 0],
        [1, 1]])

In [79]:
target = torch.tensor([2, 1, 0, 0])
preds = torch.tensor([2, 1, 0, 1])

metric = MulticlassConfusionMatrix(num_classes=3)
metric(preds, target)

tensor([[1, 1, 0],
        [0, 1, 0],
        [0, 0, 1]])